// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC0T1U6TQWir1CinCKOhpg_Hu-YyOgMj8',
    appId: '1:527711742231:web:0543e3169de7ba5a9faf52',
    messagingSenderId: '527711742231',
    projectId: 'crudapp-d453f',
    authDomain: 'crudapp-d453f.firebaseapp.com',
    storageBucket: 'crudapp-d453f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD009dsAPbDuCuawqBLcsMalEsXsaDA1GY',
    appId: '1:527711742231:android:0de9bd2a21c9614f9faf52',
    messagingSenderId: '527711742231',
    projectId: 'crudapp-d453f',
    storageBucket: 'crudapp-d453f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl6JUtn_L392AAYS8DIDruVSyNwra54K0',
    appId: '1:527711742231:ios:5482ae328927513d9faf52',
    messagingSenderId: '527711742231',
    projectId: 'crudapp-d453f',
    storageBucket: 'crudapp-d453f.appspot.com',
    iosBundleId: 'com.example.basicCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl6JUtn_L392AAYS8DIDruVSyNwra54K0',
    appId: '1:527711742231:ios:3c3c14777c587c499faf52',
    messagingSenderId: '527711742231',
    projectId: 'crudapp-d453f',
    storageBucket: 'crudapp-d453f.appspot.com',
    iosBundleId: 'com.example.basicCrudApp.RunnerTests',
  );
}
